/**
 * Rootie — Family Summary Service
 *
 * Maintains a compact text summary of each family.
 * This is passed to OpenAI INSTEAD of the full conversation history,
 * keeping token usage low.
 *
 * Example summary:
 *   "Parent: Priya. Children: Tara (age 5, slow-to-warm, shows empathy toward
 *   younger children), Arjun (age 8, curious, challenges with transitions).
 *   Recent focus: bedtime routines."
 *
 * The summary is regenerated by the AI after every 10th conversation
 * or when child profile data changes.
 */

const { query }  = require('../db/database');
const { logger } = require('../utils/logger');

// ─── Get the current family summary ──────────────────────────────────────
async function getFamilySummary(userId) {
  const result = await query(
    `SELECT summary_text FROM family_summary WHERE user_id = $1 LIMIT 1`,
    [userId]
  );
  return result.rows[0]?.summary_text || null;
}

// ─── Save or update the family summary ───────────────────────────────────
async function saveFamilySummary(userId, summaryText) {
  await query(
    `INSERT INTO family_summary (user_id, summary_text, updated_at)
     VALUES ($1, $2, NOW())
     ON CONFLICT (user_id) DO UPDATE
       SET summary_text = $2, updated_at = NOW()`,
    [userId, summaryText]
  );
}

// ─── Build a basic summary from DB data (no AI needed) ───────────────────
// Used when no AI-generated summary exists yet.
function buildBasicSummary(user, children) {
  const parts = [`Parent: ${user.parent_name || 'Unknown'}.`];
  if (children.length) {
    const childParts = children.map(c => {
      let s = `${c.child_name} (age ${c.child_age || '?'})`;
      if (c.temperament) s += `, ${c.temperament}`;
      if (c.strengths)   s += `, strengths: ${c.strengths}`;
      if (c.challenges)  s += `, challenges: ${c.challenges}`;
      return s;
    });
    parts.push(`Children: ${childParts.join('; ')}.`);
  }
  return parts.join(' ');
}

module.exports = {
  getFamilySummary,
  saveFamilySummary,
  buildBasicSummary,
};
